import './globals.css'
import type { Metadata } from 'next'
import Provider from '@/components/Provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Provider>
        <body className='min-h-screen bg-gradient-to-t  from-purple-300 to bg-purple-400'>
          {children}
        </body>
      </Provider>
    </html>
  )
}
